template: Hello {0}, it''s {1} 

management:
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  server:
    port: 8081